sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release